/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientconnessione;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author mattia
 */
public class grafica extends javax.swing.JFrame{
Connessione con=new Connessione();
static String messaggio;
ChatMulticast cm=new ChatMulticast();
gioco g=new gioco();
int dif,atempt=0;
int i=0;
String inputValue;
String es[], risposta[];
    /**
     * Creates new form grafica
     */
    public grafica() {
        dif=g.difficoltà();
        es=new String[6];
        risposta=new String[2];
        con.conntetti();
        con.scrivi(Integer.toString(dif));
        con.leggi();
        inputValue = JOptionPane.showInputDialog("Inserisci nome");
        
        cm.start();
        initComponents();
         
    }
    public grafica(int i){}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelT = new javax.swing.JLabel();
        jtext = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        invio = new javax.swing.JButton();
        InviaC = new javax.swing.JButton();
        Cancella = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelT.setText("STRIKEBALL");

        Text.setEditable(false);
        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        jLabel1.setText("1");
        jLabel1.setAutoscrolls(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("2");
        jLabel2.setAutoscrolls(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("3");
        jLabel3.setAutoscrolls(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("4");
        jLabel4.setAutoscrolls(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("5");
        jLabel5.setAutoscrolls(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("6");
        jLabel6.setAutoscrolls(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setText("7");
        jLabel7.setAutoscrolls(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("8");
        jLabel8.setAutoscrolls(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setText("9");
        jLabel9.setAutoscrolls(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel0.setText("0");
        jLabel0.setAutoscrolls(true);
        jLabel0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel0MouseClicked(evt);
            }
        });

        invio.setText(">");
        invio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invioMouseClicked(evt);
            }
        });

        InviaC.setText("Invia");
        InviaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InviaCMouseClicked(evt);
            }
        });

        Cancella.setText("Cancella");
        Cancella.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancellaMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel0))
                                    .addComponent(Cancella)))
                            .addComponent(jLabel11)
                            .addComponent(InviaC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT)
                                    .addComponent(jLabel10))))
                        .addGap(24, 24, 24))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtext, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invio)
                    .addComponent(InviaC)
                    .addComponent(Cancella))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelT)
                .addGap(9, 9, 9)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel0)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel1.getForeground()!=Color.red){
                jLabel1.setForeground(Color.red);
                g.crea("1");
                i++;
            }
            else{
                jLabel1.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel2.getForeground()!=Color.red){
                jLabel2.setForeground(Color.red);
                g.crea("2");
                
                i++;
            }
            else{
                jLabel2.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel3.getForeground()!=Color.red){
                jLabel3.setForeground(Color.red);
                g.crea("3");
                
                i++;
            }
            else{
                jLabel3.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel4.getForeground()!=Color.red){
                jLabel4.setForeground(Color.red);
                g.crea("4");
                
                i++;
            }
            else{
                jLabel4.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel5.getForeground()!=Color.red){
                jLabel5.setForeground(Color.red);
                g.crea("5");
                
                i++;
            }
            else{
                jLabel5.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel6.getForeground()!=Color.red){
                jLabel6.setForeground(Color.red);
                g.crea("6");
                
                i++;
            }
            else{
                jLabel6.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel7.getForeground()!=Color.red){
                jLabel7.setForeground(Color.red);
                g.crea("7");
               
                i++;
            }
            else{
                jLabel7.setForeground(Color.black);
                g.togli();
                i--;
            }
             jLabel10.setText(g.cod);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel8.getForeground()!=Color.red){
                jLabel8.setForeground(Color.red);
                g.crea("8");
                
                i++;
            }
            else{
                jLabel8.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel9.getForeground()!=Color.red){
                jLabel9.setForeground(Color.red);
                g.crea("9");
                
                i++;
            }
            else{
                jLabel9.setForeground(Color.black);
                g.togli();
                i--;
            }
            jLabel10.setText(g.cod);
        }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseClicked
        if(i<4 && atempt<dif){
            if(jLabel0.getForeground()!=Color.red){
                jLabel0.setForeground(Color.red);
                g.crea("0");
               
                i++;
            }
            else{
                jLabel0.setForeground(Color.black);
                g.togli();
                i--;
            }
             jLabel10.setText(g.cod);
        }
        
    }//GEN-LAST:event_jLabel0MouseClicked

    private void CancellaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancellaMouseClicked

        
        switch (g.togli()){
            case '0':
                jLabel0.setForeground(Color.black);
                break;
            case '1':
                jLabel1.setForeground(Color.black);
                break;
            case '2':
                jLabel2.setForeground(Color.black);
                break;
            case '3':
                jLabel3.setForeground(Color.black);
                break;
            case '4':
                jLabel4.setForeground(Color.black);
                break;
            case '5':
                jLabel5.setForeground(Color.black);
                break;
            case '6':
                jLabel6.setForeground(Color.black);
                break;
            case '7':
                jLabel7.setForeground(Color.black);
                break;
            case '8':
                jLabel8.setForeground(Color.black);
                break;
            case '9':
                jLabel9.setForeground(Color.black);
                break;
        }
        jLabel10.setText(g.cod);
        i--;
    }//GEN-LAST:event_CancellaMouseClicked

    private void InviaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InviaCMouseClicked
        
            if(i==4){

                jLabel0.setForeground(Color.black);
                jLabel1.setForeground(Color.black);
                jLabel2.setForeground(Color.black);
                jLabel3.setForeground(Color.black);
                jLabel4.setForeground(Color.black);
                jLabel5.setForeground(Color.black);
                jLabel6.setForeground(Color.black);
                jLabel7.setForeground(Color.black);
                jLabel8.setForeground(Color.black);
                jLabel9.setForeground(Color.black);
                con.scrivi(g.cod);
                es[atempt]=jLabel10.getText();
                g.cod="";
                jLabel10.setText("");
                i=0;
                risposta=con.leggi();

                if(Integer.parseInt(risposta[0])==1111){
                   jLabel10.setText("CONGRATULAZIONI HAI VINTO");
                   atempt++;
                   cm.invia(inputValue+" ha vinto impiegando "+atempt+" tentativi");
                   con.chiudi(); 
                }
                else{
                    
                    es[atempt]=es[atempt]+" Strike: "+risposta[0]+" Ball: "+risposta[1];
                    jList1.setListData(es);
                    atempt=atempt+1;
                    System.out.println("tentativi :"+atempt+" dif: "+dif);
                    if(atempt==dif){
                        jLabel10.setText("MI DISPIACE HAI PERSO");
                    }
                }

            }
        
        
    }//GEN-LAST:event_InviaCMouseClicked

    private void invioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invioMouseClicked
       
        cm.invia(inputValue+":\n"+jtext.getText());

    }//GEN-LAST:event_invioMouseClicked
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancella;
    private javax.swing.JButton InviaC;
    public static javax.swing.JTextArea Text;
    private javax.swing.JButton invio;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField jtext;
    // End of variables declaration//GEN-END:variables

    
   
}
